# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-trial

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_48e32abec96c415bbebc95b40b642dd4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_149519b3b6724946b17bda140d433cc0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_48e32abec96c415bbebc95b40b642dd4 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-trial'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8d495b16efa54e87aad007b49368e3a5 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_48e32abec96c415bbebc95b40b642dd4 }}/appsvc/staticsite:${{ github.sha }}'